[[redirects]]
  from = "/null"
  to = "https://www.google.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/null/index.html"
  to = "https://www.google.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/null.html"
  to = "https://www.google.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}